#include <stdio.h>

#include "exec_tree.c"

static struct WS_statement PROGRAM[] = {
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_LABEL, .label = "1100001" },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_PUSH, .num = 0 },
{ WS_POP },
{ WS_LABEL, .label = "11010001101001" },
{ WS_END },
};

int main() {
    struct wstree_err* err = wsexecute(PROGRAM, sizeof(PROGRAM) / sizeof(struct WS_statement));
    if (err) {
        fprintf(stderr, "ERROR at position %zu: %s", err->index, err->message);
        return 1;
    }
    return 0;
}
