name: Build C components

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        target: [ c, common, python ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        enable-cache: true
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        architecture: x64
    - name: Run make
      run: make ${{ matrix.target }}
